name: Initialize Dependencies
description: Install project dependencies

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.10"

outputs:
  python-version:
    description: Same as input
    value: ${{ inputs.python-version }}

runs:
  using: composite
  steps:
    - run: echo
      shell: bash
