name: Initialize Project
description: Clone repo and install project dependencies

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.10"

runs:
  using: composite
  steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with: {fetch-depth: 0}
    - name: Get commit date
      id: commit-date
      run: TZ=America/Chicago git show -s --format=%cd --date=format-local:"::set-output name=date::%Y.%m.%d"
      shell: bash

outputs:
  commit-date:
    description: Commit date
    value: ${{ steps.commit-date.outputs.date }}
  python-version:
    description: Same as input
    value: ${{ inputs.python-version }}
