name: Deploy

# TODO: first section always latest, don't overengineer

on:
  pull_request:
  push:
    # Staging
    branches: ["**"]
    branches-ignore: ["**_pr"]
    # Production
    tags: ["[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]"]

env:
  BASEURL_PROD: https://robpol86.com/
  BASEURL_STAGE: https://rob86stage.robpol86.com/
  HTML_ROOT: ./docs/_build/html
  IS_PROD: "${{ startsWith(github.ref, 'refs/tags/') && 'true' || '' }}"
  PYTHON_VERSION: "3.10"

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          no-dev: "true"
      - name: Build docs
        env:
          SPHINX_HTML_BASEURL: "${{ env.IS_PROD && env.BASEURL_PROD || env.BASEURL_STAGE }}"
        run: make docs
      - name: Store HTML as temporary artifact
        uses: actions/upload-artifact@v2
        with:
          name: html
          if-no-files-found: error
          path: "${{ env.HTML_ROOT }}"
      - name: Get version
        id: version
        env:
          AWK_PROGRAM: |
            match($0, /([0-9]{4})[^0-9]([0-9]{1,2})[^0-9]([0-9]{1,2})[[:space:]]*$/, ymd) {
              printf("::set-output name=VERSION::%d.%d.%d\n", ymd[1], ymd[2], ymd[3])
              flag = 1
              exit
            }
            END { exit !flag }
        run: ${{ env.IS_PROD && 'printenv GITHUB_REF_NAME' || 'poetry version' }} |awk "$AWK_PROGRAM"
    outputs:
      version: "${{ steps.version.outputs.VERSION }}"

  changelog:
    name: Read Changelog
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: repo
      - name: Isolate first section
        env:
          AWK_PROGRAM: |
            /^## \[[0-9]/ {
              if (flag) exit
              flag = 1
            }
            flag {
              print
              print >> "section.md"
            }
            END {
              exit !flag
            }
          VERSION: "${{ needs.build.outputs.version }}"  # e.g. 2022.4.1
        run: awk -v VERSION="$VERSION" "$AWK_PROGRAM" repo/CHANGELOG.md
