name: Diff

on:
  pull_request:
    types:
      # Defaults
      - opened
      - synchronize
      - reopened
      # Additional
      - closed

env:
  STORAGE_BRANCH: _last_merged_pr_html

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          no-dev: "true"
      - name: Build docs
        env:
          SPHINX_GITHUB_BRANCH: main
          SPHINX_HTML_BASEURL: "https://rob86stage.robpol86.com/"
        run: make docs
      - name: Prettify
        uses: ./.github/actions/prettify
        with:
          path: build/html
      - name: Store HTML as Temporary Artifact
        if: github.event.action != 'closed'
        uses: actions/upload-artifact@v3
        with:
          name: html_feature
          if-no-files-found: error
          path: build/html/
      - name: Store HTML in Orphaned Branch
        if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: "[skip ci]"
          force_orphan: true
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_branch: "${{ env.STORAGE_BRANCH }}"
          publish_dir: ./build
