name: Diff

on:
  pull_request:

jobs:

  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with: {path: html, key: "${{ runner.os }}-html"}
      - name: Diff
        id: diff
        run: |
          diff --color=always --recursive html/pre/ html/feature/ || true
          diff --color=never --recursive html/pre/ html/feature/ > all.diff || true
          if [ -s all.diff ]; then
            echo "::set-output name=nonzero::true"
            cp all{,-orig}.diff
            head -c 261445 all-orig.diff > all.diff
            if ! cmp -s all{,-orig}.diff; then
              echo -e "\n\nTruncated" >> all.diff
            fi
          fi
      - name: Post diff to PR if any changes are detected
        if: "${{ steps.diff.outputs.nonzero }}"
        uses: actions/github-script@v5
        with:
          script: |
            const {promises: fs} = require('fs')
            const diff = (await fs.readFile('all.diff', 'utf8')).trim()
            var body = '```diff\n' + diff + '\n```\n'

            // If diff is large collapse it to reduce clutter in the PR.
            let numLines = diff.match(/^/mg).length
            if (numLines > 25) {
              body = '<details>\n<summary>Show ' + numLines + ' lines</summary>\n\n' + body + '\n</details>'
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '### Diff against Prerelease Tag\n\n' + body
            })
