name: Diff

on:
  pull_request:

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Initialize dependencies, uses: ./.github/actions/init-deps}
      - {name: Build docs, run: make docs, env: {SPHINX_HTML_BASEURL: "https://rob86stage.robpol86.com/", SPHINX_GITHUB_BRANCH: main}}
      - {name: Prettify, uses: ./.github/actions/prettify, with: {path: build/html}}
      - name: Store HTML
        uses: actions/upload-artifact@v2
        with: {name: html_feature, path: build/html/, if-no-files-found: error}

  fetch:
    name: Fetch Prerelease HTML
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - name: Download prerelease artifact
        run: |
          mkdir build
          until wget "https://github.com/${{ github.repository }}/releases/download/prerelease/html.tar.gz" -O html.tar.gz; do
            sleep 5
          done
          tar -C build -xzvf html.tar.gz
        timeout-minutes: 1
      - name: Prettify
        uses: ./.github/actions/prettify
        with: {path: build/html}
      - name: Store HTML
        uses: actions/upload-artifact@v2
        with: {name: html_pre, path: build/html/, if-no-files-found: error}

  diff:
    runs-on: ubuntu-latest
    needs: [fetch, build]
    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with: {path: html, key: "${{ runner.os }}-html"}
      - {name: Fetch this feature build, uses: actions/download-artifact@v2, with: {name: html_feature, path: html/feature}}
      - {name: Fetch latest prerelease, uses: actions/download-artifact@v2, with: {name: html_pre, path: html/pre}}
      - {name: Clean, run: "find . '(' -name __pycache__ -o -name .doctrees ')' -type d -exec rm -rv {} +"}
      - name: Diff
        id: diff
        run: |
          diff --color=always --recursive html/pre/ html/feature/ || true
          diff --color=never --recursive html/pre/ html/feature/ > all.diff || true
          if [ -s all.diff ]; then
            echo "::set-output name=nonzero::true"
            cp all{,-orig}.diff
            head -c 261445 all-orig.diff > all.diff
            if ! cmp -s all{,-orig}.diff; then
              echo -e "\n\nTruncated" >> all.diff
            fi
          fi
      - name: Post diff to PR if any changes are detected
        if: "${{ steps.diff.outputs.nonzero }}"
        uses: actions/github-script@v5
        with:
          script: |
            const {promises: fs} = require('fs')

            const head = `\
              ### Diff from Prerelease
              <details>
              <summary>Show Diff</summary>

              \`\`\`diff
            `.replace(/^\s*/m, "")

            const body = await fs.readFile('all.diff', 'utf8')

            const tail = `\
              \`\`\`
              </details>
            `.replace(/^\s*/m, "")

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: head + body + tail
            })
