name: Diff

on:
  pull_request:
    types:
      # Defaults
      - opened
      - synchronize
      - reopened
      # Additional
      - closed

env:
  BRANCH_NAME_HTML_OLD: __diff__html_old
  PRETTIER_GLOB: "**/*.{js,css,html,xml}"
  ROOT_DIR_DIFF: ./build/html

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize dependencies
        uses: Robpol86/actions-init-deps-py@v3
        with:
          no-dev: "true"
      - name: Build docs
        env:
          SPHINX_GITHUB_BRANCH: main
          SPHINX_HTML_BASEURL: "https://rob86stage.robpol86.com/"
        run: make docs
      - name: Prettify
        run: |
          set -eux
          npm install -g prettier @prettier/plugin-xml
          prettier --write "$ROOT_DIR_DIFF/$PRETTIER_GLOB"
      - name: Store HTML as temporary artifact
        if: github.event.action != 'closed'
        uses: actions/upload-artifact@v3
        with:
          name: html_new
          if-no-files-found: error
          path: "${{ env.ROOT_DIR_DIFF }}"
      - name: Store HTML in orphaned branch
        if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: "[skip ci]"
          enable_jekyll: true  # Don't create .nojekyll
          force_orphan: true  # Discard git history
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_branch: "${{ env.BRANCH_NAME_HTML_OLD }}"
          publish_dir: "${{ env.ROOT_DIR_DIFF }}"

  diff:
    name: Diff
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fetch old HTML
        uses: actions/checkout@v3
        with:
          ref: "${{ env.BRANCH_NAME_HTML_OLD }}"
      - name: Fetch new HTML
        uses: actions/download-artifact@v3
        with:
          name: html_new
          path: .
      - name: Diff
        run: git status && git diff HEAD
