name: Deploy to Stage

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - {name: Initialize, uses: ./.github/actions/init, id: init}
      - {name: Build docs, run: make docs, env: {SPHINX_HTML_BASEURL: "https://rob86stage.robpol86.com/"}}
      - {name: Store HTML, uses: actions/upload-artifact@v2, with: {name: html, path: build/html/, if-no-files-found: error}}
    outputs:
      commit-date: ${{ steps.init.commit-date }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    concurrency: "publish-${{ github.event_name }}"
    steps:
      - name: Fetch HTML files
        uses: actions/download-artifact@v2
        with: {name: html, path: html}
      - run: ls -lah

  prerelease:
    runs-on: ubuntu-latest
    needs: [build, publish]
    if: "github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, ' (#')"
    env:
      tag: ${{ needs.build.outputs.commit-date }}-pre
    steps:
      - name: Gather data
        id: data
        run: |
          jq -r .head_commit.message < "$GITHUB_EVENT_PATH" > message.txt
          head -1 message.txt |sed 's/ (#[0-9]\+)$//' |xargs -0 printf '::set-output name=title::%s'
          tail -n+3 message.txt > body.txt
      - name: Fetch HTML files
        uses: actions/download-artifact@v2
        with: {name: html, path: html}
      - name: Archive HTML files
        run: tar -czvf html.tar.gz html/
      - name: Create "-pre" tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.data.tag }}',
              sha: context.sha
            })
      - name: Create prerelease
        uses: softprops/action-gh-release@v1
        with: {prerelease: true, tag_name: "${{ env.tag }}", files: "html.tar.gz", name: "${{ steps.data.title }}", body_path: body.txt}
